### ISSUE TITLE
CssSyntaxError in the stdin auto generated file

### ISSUE THREAD

**Issue by czipperz** [jenius/autoprefixer-stylus#19]
Output of 

    stylus -u autoprefixer-stylus < stylus/style.styl > style.css

is

    /usr/lib/node_modules/autoprefixer-stylus/node_modules/autoprefixer-core/node_modules/postcss/lib/input.js:46
    throw new CssSyntaxError(this, message, line, column);
          ^
    CssSyntaxError: /home/czipperz/chsWebsiteDraft/stdin:92:1: Unknown word
    at Input.error (/usr/lib/node_modules/autoprefixer-stylus/node_modules/autoprefixer-core/node_modules/postcss/lib/input.js:46:11)
    at Parser.word (/usr/lib/node_modules/autoprefixer-stylus/node_modules/autoprefixer-core/node_modules/postcss/lib/parser.js:163:18)
    at Parser.loop (/usr/lib/node_modules/autoprefixer-stylus/node_modules/autoprefixer-core/node_modules/postcss/lib/parser.js:36:16)
    at Function.module.exports (/usr/lib/node_modules/autoprefixer-stylus/node_modules/autoprefixer-core/node_modules/postcss/lib/parse.js:11:10)
    at PostCSS.process (/usr/lib/node_modules/autoprefixer-stylus/node_modules/autoprefixer-core/node_modules/postcss/lib/postcss.js:47:24)
    at Autoprefixer.process (/usr/lib/node_modules/autoprefixer-stylus/node_modules/autoprefixer-core/lib/autoprefixer.js:65:31)
    at Array.<anonymous> (/usr/lib/node_modules/autoprefixer-stylus/index.js:41:26)
    at Renderer.render (/usr/lib/node_modules/stylus/lib/renderer.js:114:27)
    at ReadStream.<anonymous> (/usr/lib/node_modules/stylus/bin/stylus:589:11)
    at ReadStream.emit (events.js:129:20)

Using the same command but without autoprefixer will work without error:

    stylus -m < stylus/style.styl > style.css

What is the problem here?

Style folder at [link](https://github.com/czipperz/chsWebsiteDraft/tree/master/stylus)

**Comment by jenius** [comment]
Hey @czipperz -- the issue here is a syntax error in your stylus, as the error mentions. The error is not clear about which file or line it's on for sure, which is annoying, but this has nothing to do with autoprefixer-stylus, and I currently don't have the bandwidth to debug your personal css files, so unfortunately I have to close this out.

That being said, here's my recommendation for debugging this yourself. Take each individual file and try to compile it by itself. Eventually one of them will error out, now you have narrowed the error down to one file. Now scan that file for any funny-looking syntax, if you find any, fix it up. If not, start removing sections of the file and compiling again until it passes, this way you will narrow it down to one section of the file.

It's a pain, but it would be avoided if you use a proper build system rather than compiling via command line. Both stylus and autoprefixer have excellent error reporting, but when you are piping the input through stdin (which is what happens when you run a command line compile via stylus), it will not give you as verbose of output about the filename or line that the error is on.

Hope this helps, and good luck debugging!
